CREATE TABLE IF NOT EXISTS TOPIC(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TOPIC_ID VARCHAR NOT NULL,
    LATEST_OPERATION_ID INT NOT NULL,
    OWNER_ID VARCHAR NOT NULL

);
CREATE TABLE IF NOT EXISTS NOTIFY_INDICATIONS(
    OPERATION_ID INT PRIMARY KEY,
    T_ID VARCHAR,
    foreign key(T_ID) REFERENCES TOPIC(TOPIC_ID),
    EVENT SMALLINT NOT NULL,
    IS_HISTORICAL BOOLEAN NOT NULL,
    MESSAGE VARCHAR NOT NULL,
    PUBLISHER_ID VARCHAR NOT NULL,
    DETAILS BINARY NOT NULL
);