/**
 * 
 */
package pl.edu.pjwstk.mteam.core;

/**
 * Class containing constants representing errors generated by nodes.
 * 
 * @author Paulina Adamska s3529@pjwstk.edu.pl
 *
 */
public class NodeError {
	//TODO: Modify the values to fit the PubSubConstants.RESP.... 
	/**
	 * Operation successful
	 */
	public static final int NOERR = -1; 
	/**
	 * Error during joining overlay
	 */
	public static final int BOOTSTRAPERR = 0; 
	/**
	 * User not found error
	 */
	public static final int ULOOKUPERR = 1;
	/**
	 * Resource not found error
	 */
	public static final int RLOOKUPERR = 2;
	/**
	 * Error inserting object to DHT
	 */
	public static final int INSERTERR = 3;
	/**
	 * Error during topic creation - topic already exists
	 */
	public static final int TOPICEXISTSERR = 4;
	/**
	 * Error during topic subscription - topic doesn't exist
	 */
	public static final int NOSUCHTOPICERR = 5;
	/**
	 * Error during topic subscription - node can't subscribe
	 * for the topic due to access control.
	 */
	public static final int AUTHERR = 6;
	/**
	 * Error during the unsubscribing process - the specified subscriber doesn't exist.
	 */
	public static final int NOSUCHSUBSCRIBERERR = 7;
}
