/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Viewer.java
 *
 * Created on 2010-01-14, 13:49:25
 */

package pl.edu.pjwstk.mteam.pubsub.topology.maintenance.test;

import java.awt.Dimension;
import java.util.Random;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author buti
 */
public class Viewer extends javax.swing.JFrame {

    public TopologyPainter painter = null;
    private int node_name_x = 11;
    private int node_id_x = 11;

    /** Creates new form Viewer */
    public Viewer() {
        initComponents();
        initComponents2();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_TopicChooser = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("New Node");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText("Refresh");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jLabel1.setText("Select topic:");
        jToolBar1.add(jLabel1);

        jComboBox_TopicChooser.setModel(new javax.swing.DefaultComboBoxModel(new String[] {""}));
        jComboBox_TopicChooser.setToolTipText("Select Topic to view topology structure for it.");
        jComboBox_TopicChooser.setMaximumSize(new java.awt.Dimension(130, 25));
        jComboBox_TopicChooser.setMinimumSize(new java.awt.Dimension(130, 25));
        jComboBox_TopicChooser.setPreferredSize(new java.awt.Dimension(130, 25));
        jComboBox_TopicChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TopicChooserActionPerformed(evt);
            }
        });
        jToolBar1.add(jComboBox_TopicChooser);

        jCheckBox1.setFont(new java.awt.Font("DejaVu Sans", 0, 10)); // NOI18N
        jCheckBox1.setText("Show other nodes");
        jCheckBox1.setFocusable(false);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jCheckBox1);
        jToolBar1.add(jSeparator2);

        jButton3.setText("Exit");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 772, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.painter.repaint();
        this.painter.showAllNodes(this.jComboBox_TopicChooser.getSelectedItem().toString(),this.jCheckBox1.isSelected());
    }//GEN-LAST:event_jButton2ActionPerformed
    Random r = new Random();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        final String node_data = "node" + node_name_x + "|" + node_id_x;
        final String str = JOptionPane.showInputDialog(null, "Enter the name and id_dist [name|id] :\n(auto: " + node_data + ")",
                "zz", 1);
        if (str != null && str.length() > 0 && str.indexOf("|") > 0) {
            node_id_x+=1;
            node_name_x+=1;
            java.awt.EventQueue.invokeLater(new Runnable() {
                private NodePainter np;
                public void run() {
                    np = new NodePainter(str.substring(0, str.indexOf("|")), str.substring(str.indexOf("|") + 1));
                    painter.add_(np);
                    np.setInfoBox(jTextArea1);
                    np.setBounds(r.nextInt(painter.getWidth() - 100), r.nextInt(painter.getHeight() - 100), np.getWidth(), np.getHeight());
                    np.setOwner(painter);
                }
            });
        } else {
            node_id_x+=1;
            node_name_x+=1;
            java.awt.EventQueue.invokeLater(new Runnable() {
                private NodePainter np;
                public void run() {
                    np = new NodePainter(node_data.substring(0, node_data.indexOf("|")), node_data.substring(node_data.indexOf("|") + 1));
                    painter.add_(np);
                    np.setInfoBox(jTextArea1);
                    np.setBounds(r.nextInt(painter.getWidth() - 100), r.nextInt(painter.getHeight() - 100), np.getWidth(), np.getHeight());
                    np.setOwner(painter);
                }
            });
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        this.painter.showAllNodes(this.jComboBox_TopicChooser.getSelectedItem().toString(),((JCheckBox)evt.getSource()).isSelected());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox_TopicChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TopicChooserActionPerformed
        this.painter.showAllNodes(this.jComboBox_TopicChooser.getSelectedItem().toString(),this.jCheckBox1.isSelected());
    }//GEN-LAST:event_jComboBox_TopicChooserActionPerformed

    public void initComponents2() {
        this.painter = new TopologyPainter();
        this.painter.setPreferredSize(new Dimension(this.jPanel2.getWidth(), this.jPanel2.getHeight()));
        this.painter.setSize(this.painter.getPreferredSize());
        jPanel2.add(this.painter);
        this.painter.setOwner(this.jPanel2);
        makeFirstNode(this.painter);       
        this.painter.repaint();
        this.painter.setMainController(this);
        this.jCheckBox1.setSelected(true);
        
        //pack();
    }
    public NodePainter rootNode = null;
    private void makeFirstNode(TopologyPainter owner){
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
                rootNode = new NodePainter("node10", "10");
                painter.add_(rootNode);
                rootNode.setInfoBox(jTextArea1);
                rootNode.setBounds(r.nextInt(painter.getWidth() - 100), r.nextInt(painter.getHeight() - 100), rootNode.getWidth(), rootNode.getHeight());
                rootNode.setOwner(painter);
                rootNode.createTopic("first", true);

            }
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Viewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox_TopicChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables

    void onTopicCreate(Object topicID) {
        int index = this.jComboBox_TopicChooser.getSelectedIndex();
        this.jComboBox_TopicChooser.addItem(topicID);
        this.jComboBox_TopicChooser.setSelectedIndex(index);
        this.jComboBox_TopicChooser.repaint();
    }
}
